server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/citizenDB
    password: citizenDB
    username: citizenDB
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MYSQL5InnoDBDialect
  application:
    name: CitizenService