server:
  port: 8083
spring:
  application:
    name: API_GATEWAY

  cloud:
    gateway:
      routes:
        - id: VaccinationCenterService
          uri:  lb://VaccinationCenterService
          predicates:
            - Path=/vaccination/**

        - id: CitizenService
          uri: lb://CitizenService
          predicates:
            - Path=/citizen/**

#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id:CitizenService
#          - uri: lb://CitizenService
#            predicates:
#              - Path=/citizen/**
#
#          - id:VaccinationService
#          - uri: lb://VaccinationService
#
#            predicates:
#              - Path=/vaccination/**